language: python
python:
  - 3.7
services:
  - docker
script:
  - docker build -t hello .
  - docker run -d -p 80:8000 --name django hello

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
