language: python
python:
- 3.7
services:
- docker
script:
- docker build -t hello .
- docker run -d -p 80:8000 --name django hello
addons:
  ssh_known_hosts: 206.189.44.192
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
